language: node_js

sudo: false
dist: trusty

node_js:
  - '8'

cache:
  directories:
    - node_modules

before_install: if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi

install:
  - travis_retry npm i

before_script:

script:
  - npm run lint:ci
  - npm run build:prod

git:
  depth: 1

deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET_NAME
  skip_cleanup: true
  region: $AWS_DEFAULT_REGION
  local_dir: dist
